project:
  type: book
  output-dir: docs

book:
  title: "LearningDiary"
  author: "Yiyang Chen"
  date: "1/18/2024"
  chapters:
    - index.qmd
    - Week01.qmd
    - Week02.qmd
    - Week03.qmd
    - Week04.qmd
    - Week06.qmd
    - Week07.qmd
    - Week08.qmd
    - Week09.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

