project:
  type: book

book:
  title: "LearningDiary"
  author: "Yiyang Chen"
  date: "1/18/2024"
  chapters:
    - index.qmd
    - Week01.qmd
    - Week02.qmd
    - Week03.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    output-dir: docx
  pdf:
    documentclass: scrreprt
    output-dir: pdf

output-dir: docx

editor: visual

